# -*- coding: utf-8 -*-
"""Language detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z981URqhavqMgNguVae3i4KNKz0hafpi
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/sample_data/language.csv')

data.head()

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

data.isnull().sum()

data ['language'].value_counts()

x = np.array(data["Text"])
y = np.array(data['language'])

print(X)

print(Y)

cv = CountVectorizer()
X = cv.fit_transform(x)

x_train, x_text, y_train, y_text = train_test_split(X, y, test_size=0.33, random_state=42)

x_train

print(x_train)

y_text

model = MultinomialNB()
model.fit(x_train, y_train)

model.score(x_text,y_text)

user = input('Enter a text')
data = cv.transform([user]).toarray()
output = model.predict(data)
print(output)